{
 "title": "Django / Requests",
 "description": "A dashboard that monitors Django. It is created using the Django-mixin for the the (Django-exporter)[https://github.com/adinhodovic/django-exporter]",
 "tags": [
  "django",
  "django-mixin"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{namespace=~\"$namespace\"}, job)"
   },
   {
    "name": "view",
    "label": "View",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{namespace=~\"$namespace\", job=~\"$job\"}, view)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{namespace=~\"$namespace\", job=~\"$job\", view=~\"$view\"}, status)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{namespace=~\"$namespace\", job=~\"$job\", view=~\"$view\", status=~\"$status\"}, method)"
   },
   { "name": "error_codes", "label": "Error Codes", "query": "4,5" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    irate(\n      django_http_requests_total_by_view_transport_method_total{namespace=~\"$namespace\", job=~\"$job\", view=~\"$view\", view!~\"health_check:health_check_home|prometheus-django-metrics\", method=~\"$method\"}[2m]\n    )\n  ), 0.001\n)\n"
    }
   ]
  },
  {
   "title": "Success Rate (non $error_codes-xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    django_http_responses_total_by_status_view_method_total{namespace=~\"$namespace\", job=~\"$job\", view=~\"$view\", view!~\"health_check:health_check_home|prometheus-django-metrics\", method=~\"$method\", status!~\"[$error_codes].*\"}[2m]\n    )\n) /\nsum(\n  rate(\n    django_http_responses_total_by_status_view_method_total{namespace=~\"$namespace\", job=~\"$job\", view=~\"$view\", view!~\"health_check:health_check_home|prometheus-django-metrics\", method=~\"$method\"}[2m]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Average Request Latency (P95) [5m]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum (\n    rate (\n        django_http_requests_latency_seconds_by_view_method_bucket {\n          namespace=~\"$namespace\",\n          job=~\"$job\",\n          view!~\"health_check:health_check_home|prometheus-django-metrics\",\n        }[5m]\n    )\n  ) by (job, le)\n)\n"
    }
   ]
  },
  {
   "title": "Average Request Body Size (P95) [5m]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum (\n    rate (\n        django_http_requests_body_total_bytes_bucket {\n          namespace=~\"$namespace\",\n          job=~\"$job\",\n        }[5m]\n    )\n  ) by (view, job, le)\n)\n"
    }
   ]
  },
  { "title": "Per View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    rate(\n      django_http_requests_latency_seconds_by_view_method_bucket{\n        namespace=~\"$namespace\",\n        job=~\"$job\",\n        view=~\"$view\",\n        view!~\"health_check:health_check_home|prometheus-django-metrics\",\n        method=~\"$method\"\n      }[5m]\n    ) > 0\n  ) by (view, job, le)\n)\n",
     "legendFormat": "50 - {{ view }}"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    rate(\n      django_http_requests_latency_seconds_by_view_method_bucket{\n        namespace=~\"$namespace\",\n        job=~\"$job\",\n        view=~\"$view\",\n        view!~\"health_check:health_check_home|prometheus-django-metrics\",\n        method=~\"$method\"\n      }[5m]\n    ) > 0\n  ) by (view, job, le)\n)\n",
     "legendFormat": "95 - {{ view }}"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    rate(\n      django_http_requests_latency_seconds_by_view_method_bucket{\n        namespace=~\"$namespace\",\n        job=~\"$job\",\n        view=~\"$view\",\n        view!~\"health_check:health_check_home|prometheus-django-metrics\",\n        method=~\"$method\"\n      }[5m]\n    ) > 0\n  ) by (view, job, le)\n)\n",
     "legendFormat": "99 - {{ view }}"
    },
    {
     "expr": "histogram_quantile(0.999,\n  sum(\n    rate(\n      django_http_requests_latency_seconds_by_view_method_bucket{\n        namespace=~\"$namespace\",\n        job=~\"$job\",\n        view=~\"$view\",\n        view!~\"health_check:health_check_home|prometheus-django-metrics\",\n        method=~\"$method\"\n      }[5m]\n    ) > 0\n  ) by (view, job, le)\n)\n",
     "legendFormat": "99.9 - {{ view }}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(\n  sum(\n    irate(\n      django_http_responses_total_by_status_view_method_total{\n        namespace=~\"$namespace\",\n        job=~\"$job\",\n        view=~\"$view\",\n        view!~\"health_check:health_check_home|prometheus-django-metrics\",\n        method=~\"$method\",\n        status=~\"$status\"\n      }[5m]\n    ) > 0\n  ) by (status, view), 0.001\n)\n",
     "legendFormat": "{{ view }} / {{ status }}"
    }
   ]
  },
  {
   "title": "Weekly Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Responses Per View (1w)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "round(\n  topk(10,\n    sum by (view) (\n      increase(\n        django_http_responses_total_by_status_view_method_total{\n          namespace=~\"$namespace\",\n          job=~\"$job\",\n          view=~\"$view\",\n          view!~\"health_check:health_check_home|prometheus-django-metrics\",\n          method=~\"$method\"\n        }[1w]\n      ) > 0\n    )\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Top Latency Per View (1w)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "round(\n  topk(10,\n    sum by (view) (\n      rate(\n        django_http_requests_latency_seconds_by_view_method_sum{namespace=~\"$namespace\", job=~\"$job\", view=~\"$view\", view!~\"health_check:health_check_home|prometheus-django-metrics\", method=~\"$method\"}[1w]\n      )\n    )\n    /\n    sum by (view) (\n      rate(\n        django_http_requests_latency_seconds_by_view_method_count{namespace=~\"$namespace\", job=~\"$job\", view=~\"$view\", view!~\"health_check:health_check_home|prometheus-django-metrics\", method=~\"$method\"}[1w]\n      )\n    )\n  ), 0.001\n) > 0\n"
      }
     ]
    },
    {
     "title": "Top Templates (1w)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "round(\n  sum by (templatename) (\n    increase(\n      django_http_responses_total_by_templatename_total{\n        namespace=~\"$namespace\",\n        job=~\"$job\",\n        templatename!~\"\\\\['health_check/index.html'\\\\]\"\n      }[1w]\n    ) > 0\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Top Error Responses Per View & Method (1w)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "round(\n  topk(10,\n    sum by (view, method) (\n      increase(\n        django_http_responses_total_by_status_view_method_total{\n          namespace=~\"$namespace\",\n          job=~\"$job\",\n          view=~\"$view\",\n          view!~\"health_check:health_check_home|prometheus-django-metrics\",\n          method=~\"$method\",\n          status=~\"[$error_codes].*\"\n        }[1w]\n      ) > 0\n    )\n  )\n)\n"
      }
     ]
    }
   ]
  }
 ]
}